### ISSUE TITLE
Don't show the footer

### ISSUE THREAD

**Issue by XiaoJianXiaoXu** [zevwings/ZVRefreshing#2]
Tht footer can't show normal for the same code . Or, where don't I noticed?
Please help me.

**Comment by zevwings** [comment]
it your rows is equal to zero, the footer will hide automatically.

**Comment by alizainprasla** [comment]
@zevwings  that not working for me. My tableview row is 0 and its keep showing.

**Comment by alizainprasla** [comment]
I am using ZVRefreshing (1.0.1)
